language: java
jdk:
  - oraclejdk8

sudo: true

services:
  - docker

os:
  - linux

branches:
  only:
    - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./gradlew buildDocker;
    docker login --username=_ --password="$HEROKU_KEY" registry.heroku.com;

    docker tag registry.heroku.com/api-contact/web:0.0.1-SNAPSHOT registry.heroku.com/api-contact-dev/web;
    docker push registry.heroku.com/api-contact-dev/web;

    docker tag registry.heroku.com/api-contact/web:0.0.1-SNAPSHOT registry.heroku.com/api-contact-qa/web;
    docker push registry.heroku.com/api-contact-qa/web;

    docker push registry.heroku.com/api-contact/web;
    fi
