version: '3'
networks:
  main:
    driver: bridge

services:
  apicontact:
    image: registry.heroku.com/api-contact/web:0.0.1-SNAPSHOT
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    networks:
      main:
  database:
    image: postgres
    environment:
        POSTGRES_DB: apicontact
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres@123
        PORT: 5432
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - postgres-db
    container_name: postgres

